'use client';
import { useEffect,useMemo,useState } from 'react';
import SpeakButton from '@/components/SpeakButton';

type Q={_id:string;question:string;options?:string[];type:string;difficulty:number;category?:string};
const fmt=(seconds:number)=>`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;

export default function ExamRunner({type,count,difficulty=0,level=0}:{type:string;count:number;difficulty?:number;level?:number}){
  const [questions,setQuestions]=useState<Q[]>([]);const [answers,setAnswers]=useState<Record<string,string>>({});const [index,setIndex]=useState(0);const [flagged,setFlagged]=useState<string[]>([]);const [startedAt]=useState(Date.now());const [elapsed,setElapsed]=useState(0);const [result,setResult]=useState<any>(null);const [loading,setLoading]=useState(true);const [submitting,setSubmitting]=useState(false);const [error,setError]=useState('');
  useEffect(()=>{const timer=window.setInterval(()=>setElapsed(Math.round((Date.now()-startedAt)/1000)),1000);return()=>window.clearInterval(timer)},[startedAt]);
  useEffect(()=>{const params=new URLSearchParams({type,count:String(count)});if(difficulty)params.set('difficulty',String(difficulty));if(level)params.set('level',String(level));fetch(`/api/exams/start?${params}`).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load exam');setQuestions(j.questions||[])}).catch((e:Error)=>setError(e.message)).finally(()=>setLoading(false))},[type,count,difficulty,level]);
  const q=questions[index];const progress=useMemo(()=>questions.length?Math.round(Object.keys(answers).length/questions.length*100):0,[answers,questions.length]);
  async function submit(){if(submitting)return;const unanswered=questions.length-Object.keys(answers).length;if(!confirm(`${unanswered?`還有 ${unanswered} 題未作答。`:''}確定交卷？`))return;setSubmitting(true);setError('');try{const res=await fetch('/api/exams/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,answers,durationSeconds:Math.round((Date.now()-startedAt)/1000),questionIds:questions.map(x=>x._id),flaggedQuestionIds:flagged})});const j=await res.json();if(!res.ok)throw new Error(j.error||'Submit failed');setResult(j)}catch(e:any){setError(e.message||'Submit failed')}finally{setSubmitting(false)}}
  if(loading)return <div className="card loading-state">Loading exam…</div>;if(error&&!questions.length)return <div className="card error-state">{error}</div>;if(!questions.length)return <div className="card">沒有足夠的已驗證題目可建立考卷。</div>;
  if(result)return <div className="list"><section className="card"><h2>Exam Result</h2><div className="grid"><div><strong>Score</strong><p>{result.score}</p></div><div><strong>Accuracy</strong><p>{result.accuracy}%</p></div><div><strong>Time</strong><p>{fmt(result.durationSeconds)}</p></div><div><strong>Correct</strong><p>{result.correct}/{result.total}</p></div><div><strong>XP</strong><p>+{result.xpEarned}</p></div><div><strong>Level</strong><p>{result.level}</p></div></div></section><section className="card"><h2>Analysis by question type</h2><div className="analysis-bars">{Object.entries(result.analysis?.byType||{}).map(([key,value]:any)=><div key={key}><div className="toolbar" style={{justifyContent:'space-between'}}><span>{key}</span><strong>{value.accuracy}%</strong></div><progress max="100" value={value.accuracy}/></div>)}</div></section><section className="card"><h2>Review answers</h2><div className="list">{result.review.map((r:any)=><details className={`review-item ${r.correct?'correct':'wrong'}`} key={r.questionId}><summary>{r.correct?'✓':'✕'} {r.question}</summary><p><strong>Your answer:</strong> {String(r.selected||'—')}</p><p><strong>Correct answer:</strong> {String(r.answer)}</p><p>{r.explanation}</p>{r.optionExplanations?.length?<ul>{r.optionExplanations.map((x:any)=><li key={x.option}><strong>{x.option}:</strong> {x.explanation}</li>)}</ul>:null}</details>)}</div></section>{(result.recommendations?.vocabularyIds?.length||result.recommendations?.grammarIds?.length)?<section className="card"><h2>Recommended review</h2><p>{result.recommendations.vocabularyIds.length} vocabulary items and {result.recommendations.grammarIds.length} grammar topics were linked to questions you missed. They are preserved in your wrong-answer history.</p></section>:null}</div>;
  return <div className="exam-layout"><section className="card"><div className="toolbar" style={{justifyContent:'space-between'}}><strong>Question {index+1}/{questions.length}</strong><span>⏱ {fmt(elapsed)}</span><span>{progress}% answered</span></div><progress max="100" value={progress}/><h2>{q.question} <SpeakButton text={q.question}/></h2>{q.options?.length?<div className="list">{q.options.map(opt=><label className={`answer-option ${answers[q._id]===opt?'selected':''}`} key={opt}><input type="radio" name={q._id} checked={answers[q._id]===opt} onChange={()=>setAnswers(a=>({...a,[q._id]:opt}))}/><span>{opt}</span><SpeakButton text={opt}/></label>)}</div>:<input className="input" value={answers[q._id]||''} onChange={e=>setAnswers(a=>({...a,[q._id]:e.target.value}))}/>}<div className="toolbar"><button className="btn" disabled={index===0} onClick={()=>setIndex(i=>i-1)}>Previous</button><button className="btn" onClick={()=>setFlagged(f=>f.includes(q._id)?f.filter(x=>x!==q._id):[...f,q._id])}>{flagged.includes(q._id)?'⚑ Unflag':'⚐ Flag'}</button><button className="btn" disabled={index===questions.length-1} onClick={()=>setIndex(i=>i+1)}>Next</button><button className="btn primary" disabled={submitting} onClick={submit}>{submitting?'Submitting…':'Submit'}</button></div>{error?<p className="danger" role="alert">{error}</p>:null}</section><aside className="card question-nav"><h3>Question Navigator</h3><div className="question-grid">{questions.map((item,i)=><button type="button" key={item._id} onClick={()=>setIndex(i)} className={`${i===index?'current':''} ${answers[item._id]?'answered':''} ${flagged.includes(item._id)?'flagged':''}`}>{i+1}</button>)}</div><p className="muted">Filled = answered · border = flagged</p></aside></div>;
}
