'use client';
import { useEffect,useRef,useState } from 'react';
import Link from 'next/link';

export default function GlobalSearch(){
  const [open,setOpen]=useState(false);const [q,setQ]=useState('');const [data,setData]=useState<any>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const controller=useRef<AbortController|null>(null);
  useEffect(()=>{const h=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setOpen(v=>!v)}if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[]);
  useEffect(()=>{if(timer.current)clearTimeout(timer.current);controller.current?.abort();const value=q.trim().slice(0,80);if(value.length<2){setData(null);setError('');setLoading(false);return}timer.current=setTimeout(async()=>{const c=new AbortController();controller.current=c;setLoading(true);setError('');try{const r=await fetch(`/api/search?q=${encodeURIComponent(value)}`,{signal:c.signal});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Search failed');setData(j)}catch(e:any){if(e?.name!=='AbortError')setError('Search temporarily unavailable.')}finally{if(controller.current===c)setLoading(false)}},250);return()=>{if(timer.current)clearTimeout(timer.current);controller.current?.abort()}},[q]);
  if(!open)return <button className="search-fab" onClick={()=>setOpen(true)} aria-label="Open global search">⌘K</button>;
  const groups=[['Vocabulary',data?.vocabulary||[],(x:any)=>`/vocabulary/${encodeURIComponent(x.word)}`,(x:any)=>x.word],['Grammar',data?.grammar||[],(x:any)=>`/grammar/${x.slug}`,(x:any)=>x.title],['Reading',data?.reading||[],(x:any)=>`/reading/${x.slug}`,(x:any)=>x.title],['Word Roots',data?.morphology||[],(x:any)=>`/word-roots/${x.slug}`,(x:any)=>x.form]] as const;
  return <div className="search-backdrop" onMouseDown={()=>setOpen(false)}><div className="search-dialog" role="dialog" aria-modal="true" aria-label="Global search" onMouseDown={e=>e.stopPropagation()}><input autoFocus className="input" maxLength={80} style={{width:'100%'}} placeholder="Search vocabulary, grammar, reading, roots…" value={q} onChange={e=>setQ(e.target.value)}/>{loading&&<p className="muted">Searching…</p>}{error&&<p className="danger" role="alert">{error}</p>}{q.trim().length<2&&<p className="muted">Type at least 2 characters.</p>}{groups.map(([name,items,href,label])=>items.length?<section key={name}><h3>{name}</h3><div className="list">{items.map((x:any)=><Link className="search-result" key={String(x._id||x.slug||label(x))} href={href(x)} onClick={()=>setOpen(false)}>{label(x)}</Link>)}</div></section>:null)}{data&&!loading&&!error&&groups.every(([,items])=>items.length===0)&&<p className="muted">No results.</p>}</div></div>;
}
