import Link from 'next/link';
import {redirect} from 'next/navigation';
import {Types} from 'mongoose';
import {auth} from '@/auth';
import {dbConnect} from '@/lib/db';
import {Vocabulary} from '@/models/Vocabulary';
import {VocabularyProgress} from '@/models/VocabularyProgress';
import {GrammarLesson,GrammarProgress,Article,ReadingProgress,ExamAttempt,GameResult,StudySession} from '@/models/Learning';
import {User} from '@/models/User';
import DailyTasks from '@/components/DailyTasks';
import {taipeiHour,taipeiLastDays,TAIPEI_TIME_ZONE} from '@/lib/time';

export const dynamic='force-dynamic';type DashboardUser={xp?:number;level?:number;streak?:number};
export default async function Dashboard(){
  const session=await auth();if(!session?.user)redirect('/login');await dbConnect();const userId=(session.user as any).id;if(!Types.ObjectId.isValid(userId))redirect('/login');const objectId=new Types.ObjectId(userId);const now=new Date();const lastDays=taipeiLastDays(7);const weekStart=lastDays[0].start;
  const [user,vocabCount,learned,mastered,due,grammar,reading,exams,games,study,recent,week,completedGrammar,completedReading,dueProgress]=await Promise.all([
    User.findById(userId).select('xp level streak').lean() as Promise<DashboardUser|null>,Vocabulary.countDocuments({published:true}),VocabularyProgress.countDocuments({userId,reviewCount:{$gt:0}}),VocabularyProgress.countDocuments({userId,status:'mastered'}),VocabularyProgress.countDocuments({userId,nextReviewAt:{$lte:now}}),GrammarProgress.countDocuments({userId,status:{$in:['completed','mastered']}}),ReadingProgress.countDocuments({userId,completedAt:{$exists:true}}),ExamAttempt.countDocuments({userId,completedAt:{$exists:true}}),GameResult.countDocuments({userId}),StudySession.aggregate([{$match:{userId:objectId}},{$group:{_id:null,seconds:{$sum:'$durationSeconds'}}}]),StudySession.find({userId}).sort({startedAt:-1}).limit(7).lean(),StudySession.aggregate([{$match:{userId:objectId,startedAt:{$gte:weekStart}}},{$group:{_id:{$dateToString:{format:'%Y-%m-%d',date:'$startedAt',timezone:TAIPEI_TIME_ZONE}},seconds:{$sum:'$durationSeconds'}}}]),GrammarProgress.find({userId,status:{$in:['completed','mastered']}}).distinct('grammarId'),ReadingProgress.find({userId,completedAt:{$exists:true}}).distinct('articleId'),VocabularyProgress.findOne({userId,nextReviewAt:{$lte:now}}).sort({nextReviewAt:1}).lean()
  ]);
  const [recommendedGrammar,recommendedReading,dueWord]=await Promise.all([GrammarLesson.findOne({published:true,_id:{$nin:completedGrammar}}).select('slug title level').sort({level:1,title:1}).lean(),Article.findOne({published:true,_id:{$nin:completedReading}}).select('slug title category difficulty').sort({difficulty:1,createdAt:-1}).lean(),dueProgress?Vocabulary.findById((dueProgress as any).vocabularyId).select('word ceecLevel').lean():null]);
  const hour=taipeiHour();const greeting=hour<12?'Good morning':hour<18?'Good afternoon':'Good evening';const weekMap=new Map(week.map((x:any)=>[x._id,Math.round(x.seconds/60)]));const days=lastDays.map(d=>({label:d.label,minutes:weekMap.get(d.key)||0}));const maxDay=Math.max(1,...days.map(x=>x.minutes));
  return <main className="content"><p className="muted">{greeting}</p><h1>{session.user.name}</h1><div className="grid stats-grid"><div className="card"><span className="muted">Published vocabulary</span><h2>{vocabCount.toLocaleString()}</h2><p>database count</p></div><div className="card"><span className="muted">Due today</span><h2>{due}</h2><Link href="/review">Start review →</Link></div><div className="card"><span className="muted">Mastered</span><h2>{mastered}</h2><p>Learned {learned}</p></div><div className="card"><span className="muted">XP / Level</span><h2>{user?.xp||0} XP</h2><p>Level {user?.level||1} · streak {user?.streak||0}</p></div><div className="card"><span className="muted">Completed activities</span><h2>{grammar+reading+exams+games}</h2><p>Grammar {grammar} · Reading {reading} · Exams {exams} · Games {games}</p></div><div className="card"><span className="muted">Study time</span><h2>{Math.round((study[0]?.seconds||0)/60)} min</h2></div></div><div style={{marginTop:16}}><DailyTasks/></div><section className="card chart-card"><div className="toolbar" style={{justifyContent:'space-between'}}><h2>7-day activity</h2><Link href="/progress">Full analytics →</Link></div><div className="bar-chart compact">{days.map((d,i)=><div className="bar-column" key={i}><div className="bar-value">{d.minutes}m</div><div className="bar" style={{height:`${Math.max(4,d.minutes/maxDay*90)}px`}}/><small>{d.label}</small></div>)}</div></section><h2>Recommended next</h2><div className="grid">{dueWord?<Link className="card" href={`/vocabulary/${encodeURIComponent((dueWord as any).word)}`}><p className="muted">Due vocabulary</p><h3>{(dueWord as any).word}</h3><p>CEEC Level {(dueWord as any).ceecLevel}</p></Link>:<Link className="card" href="/vocabulary"><p className="muted">Vocabulary</p><h3>Choose a new word</h3></Link>}{recommendedGrammar?<Link className="card" href={`/grammar/${(recommendedGrammar as any).slug}`}><p className="muted">Grammar · {(recommendedGrammar as any).level}</p><h3>{(recommendedGrammar as any).title}</h3></Link>:<Link className="card" href="/grammar"><p className="muted">Grammar</p><h3>Browse lessons</h3></Link>}{recommendedReading?<Link className="card" href={`/reading/${(recommendedReading as any).slug}`}><p className="muted">Reading · {(recommendedReading as any).category}</p><h3>{(recommendedReading as any).title}</h3></Link>:<Link className="card" href="/reading"><p className="muted">Reading</p><h3>Browse articles</h3></Link>}</div><section className="card" style={{marginTop:16}}><h2>Recent activity</h2>{recent.length?<div className="list">{recent.map((x:any)=><div className="activity-row" key={String(x._id)}><strong>{x.activity}</strong><span>{Math.round((x.durationSeconds||0)/60)} min</span><span className="muted">{x.startedAt?new Date(x.startedAt).toLocaleString('zh-TW',{timeZone:TAIPEI_TIME_ZONE}):''}</span></div>)}</div>:<p className="muted">完成第一個學習活動後，紀錄會出現在這裡。</p>}</section></main>;
}
